#!/bin/bash

make -f Makefile
if [ $? -eq 0 ]
then
	echo ""
	echo "compile successfull"
	if [ "$(id -u)" = "0" ]
	then
		echo ""
		echo "flashing firmware NKBM-ST110.hex to microcontroller"
		echo ""
		echo "switch the keyboard's microcontroller into DFU mode to begin flashing firmware"
		echo "waiting for DFU mode..."
		../../teensy_loader_cli/teensy_loader_cli --mcu=at90usb1286 -w ./NKBM-ST110_firmware.hex
		if [ $? -eq 0 ]
		then
			
			echo ""
			echo "firmware flash sucessful, keyboard rebooting..."
			echo ""
			exit 0
		else
			echo ""
			echo "firmware flash failed, exiting..."
			echo ""
			exit 1
		fi
	else
		echo ""
		echo "only root user may flash microcontroller, please run again as root, exiting..."
		echo ""

		exit 1
	fi
else
	echo ""
	echo "compile failed, skipping microcontroller flash and exiting..."
	echo ""
	exit 1
fi
