#!/bin/bash

make -f Makefile
if [ $? -eq 0 ]
then
	echo "compile successfull, flashing firmware JIS_110R.hex to microcontroller"
	echo "please enter root password THEN set the microcontroller into DFU mode to re-flash firmware"
	su -c "../../teensy_loader_cli/teensy_loader_cli --mcu=at90usb1286 -w ./JIS_110R.hex"
	if [ $? -eq 0 ]
	then
		echo "firmware flash sucessful, keyboard rebooted."
		exit 0
	else
		echo "firmware flash failed, exiting..."
		exit 1
	fi
else
	echo "compile failed, skipping microcontroller flash and exiting..."
	exit 1
fi
